# Generated by Django 5.2.15 on 2026-09-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0004_encounter_created_at_encounter_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientdocument",
            options={
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("medical_records_view_document", "Can view document"),
                    ("medical_records_add_document", "Can add document"),
                    ("medical_records_change_document", "Can change document"),
                    ("medical_records_delete_document", "Can delete document"),
                ],
            },
        ),
    ]
