# Generated by Django 5.2.15 on 2026-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_shift_created_at_shift_deleted_at_shift_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("ADMIN", "Administrator"),
                    ("TECH", "Technician"),
                    ("PHARMACIST", "Pharmacist"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("SURGEON", "Surgeon"),
                    ("ANESTHESIOLOGIST", "Anesthesiologist"),
                    ("RADIOLOGIST", "Radiologist"),
                    ("LAB_TECH", "Laboratory Technician"),
                    ("SECURITY", "Security"),
                    ("MAINTENANCE", "Maintenance"),
                    ("OTHER", "Other"),
                    ("VIEWER", "Read-only Viewer"),
                ],
                help_text="Staff member's role/position",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("ADMIN", "Administrator"),
                    ("TECH", "Technician"),
                    ("PHARMACIST", "Pharmacist"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("SURGEON", "Surgeon"),
                    ("ANESTHESIOLOGIST", "Anesthesiologist"),
                    ("RADIOLOGIST", "Radiologist"),
                    ("LAB_TECH", "Laboratory Technician"),
                    ("SECURITY", "Security"),
                    ("MAINTENANCE", "Maintenance"),
                    ("OTHER", "Other"),
                    ("VIEWER", "Read-only Viewer"),
                ],
                help_text="Staff member's role/position",
                max_length=20,
            ),
        ),
    ]
